export {default as Navigation} from './Navigation/NavigationSec'
export {default as Header} from './Header/Header'
export {default as Services} from './Services/Services'
export {default as Footer} from './Footer/Footer'
export {default as ContactUs} from './ContactUs/ContactUs'